### ISSUE TITLE
Siempre sale alebupal como usuario 

### ISSUE THREAD

**Issue by alebupal** [alebupal/tvspy#21]
Reportado por [loznic89](https://github.com/loznic89)

En la parte de los canales en vivo, sale el mismo usuario

**Comment by alebupal** [comment]
[https://github.com/alebupal/tvspy/commit/c9a9998b6d702210eabfdcfd62520e481abc9dbe](url)

**Comment by alebupal** [comment]
c9a9998b6d702210eabfdcfd62520e481abc9dbe

**Comment by loznic89** [comment]
> Arreglado en [c9a9998](https://github.com/alebupal/tvspy/commit/c9a9998b6d702210eabfdcfd62520e481abc9dbe), @loznic89 si puedes probar y confirmar que va bien me haces un favor :), tendrás que generar la imagen de nuevo

Arreglado ya si salen los usuarios que corresponden. Una ultima sugerencia: seria posible añadir estas 2 opciones que estaban en la anterior version?
- Tiempo de refresco (segundos) página de inicio
- Tiempo mínimo para registro (segundos)

**Comment by alebupal** [comment]
> > Arreglado en [c9a9998](https://github.com/alebupal/tvspy/commit/c9a9998b6d702210eabfdcfd62520e481abc9dbe), @loznic89 si puedes probar y confirmar que va bien me haces un favor :), tendrás que generar la imagen de nuevo
> 
> Arreglado ya si salen los usuarios que corresponden. Una ultima sugerencia: seria posible añadir estas 2 opciones que estaban en la anterior version?
> 
> * Tiempo de refresco (segundos) página de inicio
> * Tiempo mínimo para registro (segundos)

Puees podría plantear la segunda opción, la primera ya no es necesario ya que la app se conecta por websocket y esta leyendo constantemente desde tvheadend.

Le doy una vuelta...

**Comment by loznic89** [comment]
Vale. Sí la segunda opcion es la que quería por el tema de que no esté avisando por telegram cada vez que hay un corte. Saludos

**Comment by alebupal** [comment]
> Vale. Sí la segunda opcion es la que quería por el tema de que no esté avisando por telegram cada vez que hay un corte. Saludos

Listo en cfbba88a0a7652177c3ef3c8892860e245e1da43 ya me cuentas que tal

**Comment by loznic89** [comment]
> > Vale. Sí la segunda opcion es la que quería por el tema de que no esté avisando por telegram cada vez que hay un corte. Saludos
> 
> Listo en [cfbba88](https://github.com/alebupal/tvspy/commit/cfbba88a0a7652177c3ef3c8892860e245e1da43) ya me cuentas que tal

Perfecto. Funciona y ajustable desde la interfaz web.
Muchas gracias!!
